apiVersion: v1
kind: Service

metadata:
  name: olivetti-face-service

spec:
  type: NodePort

  selector:
    app: olivetti-face-app

  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007